1. Import the numpy package under the name np

In [115]:
import numpy as np

2. Print the numpy version and the configuration

In [116]:
print(np.__version__)
print(np.show_config())

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

3. Create a null vector of size 10

In [117]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. How to find the memory size of any array

In [118]:
print(null_vector.nbytes)

80


5. How to get the documentation of the numpy add function from the command line?

In [119]:
help(np.add)

# Or you can use:
np.info(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

6. Create a null vector of size 10 but the fifth value which is 1

In [120]:
null_vector1 = np.zeros(10)
null_vector1[4] = 1
print(null_vector1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49

In [121]:
num_vec = np.arange(10,49)
print(num_vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


8. Reverse a vector (first element becomes last)

In [122]:
reversed_vec = num_vec[::-1]
print(reversed_vec)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9. Create a 3x3 matrix with values ranging from 0 to 8

In [123]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [124]:
arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)
print(indices)

(array([0, 1, 4]),)


11. Create a 3x3 identity matrix

In [125]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Create a 3x3x3 array with random values

In [126]:
np.random.rand(3,3,3)

array([[[0.87124507, 0.27854909, 0.01618205],
        [0.37385303, 0.66355273, 0.07057732],
        [0.50164551, 0.66428656, 0.93185996]],

       [[0.3649001 , 0.02342263, 0.31784961],
        [0.8215939 , 0.45131572, 0.58948598],
        [0.77077972, 0.44003745, 0.81972454]],

       [[0.00320478, 0.30317124, 0.50108545],
        [0.45146172, 0.42325535, 0.73994106],
        [0.40595592, 0.98786611, 0.54143248]]])

13. Create a 10x10 array with random values and find the minimum and maximum values

In [127]:
rand = np.random.rand(10,10)
print(rand)
print("The Minimum is: ", rand.min())
print("The Maximum is: ", rand.max())

[[0.40857874 0.17088823 0.4142113  0.32431601 0.16397404 0.75540406
  0.66694704 0.22096935 0.49289299 0.07748731]
 [0.7972728  0.03820841 0.83378616 0.95507925 0.30643356 0.71897659
  0.11011062 0.01358378 0.46108458 0.07509653]
 [0.33141234 0.48503592 0.00330068 0.76336759 0.49879585 0.41030032
  0.95465759 0.68883848 0.64406877 0.42091712]
 [0.35363053 0.29952938 0.91531758 0.84422748 0.83040864 0.96696805
  0.83908291 0.89446558 0.58392168 0.74745714]
 [0.43990152 0.43864479 0.11671492 0.69682637 0.90804834 0.42272133
  0.92780048 0.42103463 0.51041418 0.00729731]
 [0.30940269 0.63673818 0.81261385 0.84534302 0.78206946 0.05163491
  0.68549021 0.97714385 0.07123853 0.01406002]
 [0.48679409 0.07807588 0.24229834 0.91622125 0.00224045 0.01785678
  0.94000262 0.93361756 0.29182884 0.25587577]
 [0.91195269 0.2990939  0.38066711 0.5120122  0.50848055 0.25575532
  0.7194476  0.54513871 0.42215534 0.15567661]
 [0.8392856  0.96310512 0.54921459 0.95010883 0.76587189 0.13766205
  0.29618338

14. Create a random vector of size 30 and find the mean value

In [128]:
print(np.random.rand(30))
np.random.rand(30).mean()

[7.72156531e-01 9.58822619e-02 8.49916356e-01 3.61545001e-01
 4.33570566e-01 6.11737680e-01 5.97898733e-01 1.67999582e-02
 4.32587972e-01 5.67153834e-01 8.21112134e-02 7.10671390e-04
 5.48655758e-01 8.62009182e-01 1.68360547e-02 9.30665532e-01
 7.45029484e-01 6.69147589e-01 2.61605312e-01 6.58615621e-01
 8.10483193e-01 4.85957528e-01 5.05457315e-01 3.37929730e-01
 9.92788475e-01 8.77471857e-01 2.11156820e-01 3.59793589e-01
 1.88844449e-01 6.69914506e-01]


np.float64(0.544385498257293)

15. Create a 2d array with 1 on the border and 0 inside

In [129]:
border_array = np.ones((5, 5), dtype=int)
border_array[1:-1, 1:-1] = 0
print(border_array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


16. How to add a border (filled with 0's) around an existing array?

In [130]:
padded_array = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(padded_array)

[0 1 2 0 0 4 0 0]


17. What is the result of the following expression?

0 * np.nan<br>
np.nan == np.nan<br>
np.inf > np.nan<br>
np.nan - np.nan<br>
np.nan in set([np.nan])<br>
0.3 == 3 * 0.1

In [131]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [132]:
matrix = np.diag([1, 2, 3, 4], k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [133]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [134]:
np.unravel_index(100, (6, 7, 8))

(np.int64(1), np.int64(5), np.int64(4))

21. Create a checkerboard 8x8 matrix using the tile function

In [135]:
checkerboard_tile = np.tile([[0, 1], [1, 0]], (4, 4))
print(checkerboard_tile)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22. Normalize a 5x5 random matrix

In [136]:
rand_matrix = np.random.rand(5, 5)
normalized_matrix = (rand_matrix - rand_matrix.min()) / (rand_matrix.max() - rand_matrix.min())
print(normalized_matrix)

[[0.4966844  0.65119978 0.86414608 0.65412169 0.50910967]
 [0.87992575 0.80277499 0.34086607 0.32457069 0.01748756]
 [1.         0.         0.61378249 0.29339406 0.22680298]
 [0.54877352 0.67970408 0.35449923 0.23963242 0.17918072]
 [0.78940624 0.34944688 0.52510107 0.23601095 0.7566866 ]]


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [137]:
rgba_dtype = np.dtype([('red', np.uint8), ('green', np.uint8), ('blue', np.uint8), ('alpha', np.uint8)])
print(rgba_dtype)

[('red', 'u1'), ('green', 'u1'), ('blue', 'u1'), ('alpha', 'u1')]


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [138]:
matrix1 = np.random.rand(5, 3)
matrix2 = np.random.rand(3, 2)
product_matrix = np.dot(matrix1, matrix2)
# Alternatively, you can use the @ operator for matrix multiplication:
product_matrix = matrix1 @ matrix2
print(product_matrix)

[[0.5832633  0.99164524]
 [0.69917627 1.61520514]
 [0.19750219 0.88543349]
 [0.18347197 0.56744535]
 [0.53819949 1.37754219]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place

In [139]:
arr = np.arange(10)
arr[(arr > 3) & (arr < 8)] *= -1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


26. What is the output of the following script?

print(sum(range(5),-1))

from numpy import *

print(sum(range(5),-1))

In [140]:
print(sum(range(5),-1))

from numpy import *

print(sum(range(5),-1))

10
10


27. Consider an integer vector Z, which of these expressions are legal?

Z**Z

2 << Z >> 2

Z <- Z

1j*Z

Z/1/1

Z<Z>Z

In [141]:
Z = np.arange(5) # Sample integer vector

print("Z**Z:", Z**Z)
print("2 << Z >> 2:", 2 << Z >> 2)
# print("Z <- Z:", Z <- Z) # This is not legal Python/NumPy syntax for element-wise comparison and assignment
print("1j*Z:", 1j*Z)
print("Z/1/1:", Z/1/1)
# print("Z<Z>Z:", Z<Z>Z) # This is not legal Python/NumPy syntax for chained comparison with arrays

Z**Z: [  1   1   4  27 256]
2 << Z >> 2: [0 1 2 4 8]
1j*Z: [0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
Z/1/1: [0. 1. 2. 3. 4.]


28. What are the result of the following expressions?

In [142]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

29. How to round away from zero a float array ?

In [143]:
# Create a sample float array
float_array = np.array([-1.5, -0.8, 0.2, 1.9, -2.1, 3.5])

# Round away from zero
rounded_array = np.copysign(np.ceil(np.abs(float_array)), float_array)

print(rounded_array)

[-2. -1.  1.  2. -3.  4.]


30. How to find common values between two arrays?

In [144]:
import numpy as np

# Create two sample arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values
common_values = np.intersect1d(array1, array2)

print(common_values)

[3 4 5]


31. How to ignore all numpy warnings (not recommended)?

In [145]:
# Create a scenario that would normally produce a warning (e.g., division by zero)
with np.errstate(divide='warn'):
    print(np.array([1, 2, 3]) / np.array([0, 1, 2]))

# Ignore all warnings
np.seterr(all='ignore')

# Now the division by zero warning will be suppressed
print(np.array([1, 2, 3]) / np.array([0, 1, 2]))


[inf 2.  1.5]
[inf 2.  1.5]


/tmp/ipython-input-4225702701.py:3: RuntimeWarning: divide by zero encountered in divide
  print(np.array([1, 2, 3]) / np.array([0, 1, 2]))


32. Is the following expressions true?

np.sqrt(-1) == np.emath.sqrt(-1)

In [146]:
np.sqrt(-1) == np.emath.sqrt(-1)

np.False_

33. How to get the dates of yesterday, today and tomorrow?

In [147]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2025-08-10
Today: 2025-08-11
Tomorrow: 2025-08-12


34. How to get all the dates corresponding to the month of July 2016?

In [148]:
dates_july_2016 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates_july_2016)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [149]:
import numpy as np

# Create sample arrays A and B
A = np.ones(10)
B = np.ones(10) * 2

# Compute (A+B) in place (store in A)
np.add(A, B, out=A)

# Compute (-A/2) in place (store in B)
np.divide(A, -2, out=B)

# Compute (A * B) in place (store in A)
np.multiply(A, B, out=A)

print(A)

[-4.5 -4.5 -4.5 -4.5 -4.5 -4.5 -4.5 -4.5 -4.5 -4.5]


36. Extract the integer part of a random array of positive numbers using 4 different methods

In [150]:
# Create a random array of positive numbers
random_array = np.random.uniform(0, 10, 10)
print("Original array:", random_array)

# Method 1: Using the floor function
method1 = np.floor(random_array)
print("Method 1 (floor):", method1)

# Method 2: Using astype(int)
method2 = random_array.astype(int)
print("Method 2 (astype(int)):", method2)

# Method 3: Using the trunc function
method3 = np.trunc(random_array)
print("Method 3 (trunc):", method3)

# Method 4: Using the double slash operator (integer division)
method4 = random_array // 1
print("Method 4 (integer division):", method4)

Original array: [2.40275872 7.80661011 2.40227492 0.98076757 6.94198353 3.80023759
 0.01497003 2.93370938 5.7300531  6.38722463]
Method 1 (floor): [2. 7. 2. 0. 6. 3. 0. 2. 5. 6.]
Method 2 (astype(int)): [2 7 2 0 6 3 0 2 5 6]
Method 3 (trunc): [2. 7. 2. 0. 6. 3. 0. 2. 5. 6.]
Method 4 (integer division): [2. 7. 2. 0. 6. 3. 0. 2. 5. 6.]


37. Create a 5x5 matrix with row values ranging from 0 to 4

In [151]:
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)

# Alternatively, using broadcasting:
matrix = np.arange(5) + np.zeros((5, 5), dtype=int)
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


38. Consider a generator function that generates 10 integers and use it to build an array

In [152]:
import numpy as np

def int_generator():
  for i in range(10):
    yield i

# Use the generator to build an array
array_from_generator = np.fromiter(int_generator(), dtype=int)

print(array_from_generator)

[0 1 2 3 4 5 6 7 8 9]


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [153]:
vector = np.random.rand(10)
print(vector)

[0.71921636 0.70414528 0.33999691 0.24867091 0.80920483 0.83805486
 0.4618042  0.66112954 0.43442978 0.7417836 ]


40. Create a random vector of size 10 and sort it

In [154]:
random_vector = np.random.rand(10)
print("Original vector:", random_vector)

sorted_vector = np.sort(random_vector)
print("Sorted vector:", sorted_vector)

Original vector: [0.50275902 0.44537764 0.03381241 0.6894102  0.87962607 0.17506951
 0.48568946 0.48967911 0.13963959 0.0270821 ]
Sorted vector: [0.0270821  0.03381241 0.13963959 0.17506951 0.44537764 0.48568946
 0.48967911 0.50275902 0.6894102  0.87962607]


41. How to sum a small array faster than np.sum?

In [155]:
import timeit

small_array = np.arange(10)

# Using np.sum
numpy_sum_time = timeit.timeit(lambda: np.sum(small_array), number=100000)
print(f"Time taken by np.sum: {numpy_sum_time:.6f} seconds")

# Using Python's built-in sum
python_sum_time = timeit.timeit(lambda: sum(small_array), number=100000)
print(f"Time taken by built-in sum: {python_sum_time:.6f} seconds")

Time taken by np.sum: 0.657289 seconds
Time taken by built-in sum: 0.522619 seconds


42. Consider two random array A and B, check if they are equal

In [156]:
A = np.random.rand(5)
B = np.random.rand(5)

# Check if they are equal
are_equal = np.array_equal(A, B)

print("Array A:", A)
print("Array B:", B)
print("Are arrays A and B equal?  ===> ", are_equal)

# Create two equal arrays to demonstrate
C = np.array([1, 2, 3])
D = np.array([1, 2, 3])
are_equal_cd = np.array_equal(C, D)
print("\nArray C:", C)
print("Array D:", D)
print("Are arrays C and D equal?  ===> ", are_equal_cd)

Array A: [0.43611909 0.95110261 0.4907003  0.36249185 0.82310296]
Array B: [0.09942632 0.55210528 0.78473869 0.36855558 0.77700213]
Are arrays A and B equal?  ===>  False

Array C: [1 2 3]
Array D: [1 2 3]
Are arrays C and D equal?  ===>  True


43. Make an array immutable (read-only)

In [157]:
mutable_array = np.arange(10)
print("Original array:", mutable_array)

# Make the array immutable
mutable_array.flags.writeable = False

# Attempting to modify the array will raise an error
try:
  mutable_array[0] = 100
except ValueError as e:
  print("\nError when trying to modify immutable array:", e)

print("Array after attempting modification:", mutable_array)

Original array: [0 1 2 3 4 5 6 7 8 9]

Error when trying to modify immutable array: assignment destination is read-only
Array after attempting modification: [0 1 2 3 4 5 6 7 8 9]


44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [158]:
cartesian_coordinates = np.random.rand(10, 2) * 10 - 5 # Values between -5 and 5

# Extract x and y coordinates
x = cartesian_coordinates[:, 0]
y = cartesian_coordinates[:, 1]

# Convert to polar coordinates
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x) # Use arctan2 for correct angle in all quadrants

# Combine r and theta into a single array
polar_coordinates = np.stack((r, theta), axis=1)

print("Cartesian Coordinates:\n", cartesian_coordinates)
print("\nPolar Coordinates (r, theta):\n", polar_coordinates)

Cartesian Coordinates:
 [[ 0.13252074 -0.94869027]
 [ 4.46740538  1.37699365]
 [ 3.78886983  1.34771532]
 [ 2.5064145  -0.32743262]
 [ 0.59544839  3.01157784]
 [ 3.46478002  4.58996885]
 [-2.07877636  0.69069515]
 [ 4.74683682 -1.68955827]
 [ 0.55699213 -4.12224651]
 [-0.09148138  2.74292354]]

Polar Coordinates (r, theta):
 [[ 0.95790134 -1.43200631]
 [ 4.6748072   0.29899113]
 [ 4.02142651  0.34174707]
 [ 2.52771157 -0.12990221]
 [ 3.06987945  1.37559428]
 [ 5.75087077  0.9241926 ]
 [ 2.19051842  2.82080801]
 [ 5.03855802 -0.34195098]
 [ 4.15970631 -1.43649113]
 [ 2.74444864  1.60413575]]


45. Create random vector of size 10 and replace the maximum value by 0

In [159]:
random_vector = np.random.rand(10)
print("Original vector:", random_vector)

# Find the index of the maximum value
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Vector with maximum value replaced by 0:", random_vector)

Original vector: [0.40627218 0.21415535 0.17522964 0.33502499 0.42475953 0.69792037
 0.50525748 0.40500624 0.73593508 0.91190755]
Vector with maximum value replaced by 0: [0.40627218 0.21415535 0.17522964 0.33502499 0.42475953 0.69792037
 0.50525748 0.40500624 0.73593508 0.        ]


46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

In [160]:
n_points = 5

# Create arrays for x and y coordinates
x_coords = np.linspace(0, 1, n_points)
y_coords = np.linspace(0, 1, n_points)

# Create a grid of coordinates
x_grid, y_grid = np.meshgrid(x_coords, y_coords)

# Define a custom dtype for the structured array
coordinate_dtype = np.dtype([('x', float), ('y', float)])

# Create the structured array
structured_array = np.empty((n_points, n_points), dtype=coordinate_dtype)

# Fill the structured array with the grid coordinates
structured_array['x'] = x_grid
structured_array['y'] = y_grid

print(structured_array)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [161]:
# Create sample arrays X and Y
X = np.arange(5)
Y = X + 0.5 # Ensure xi != yj

# Construct the Cauchy matrix
cauchy_matrix = 1.0 / (X[:, np.newaxis] - Y)

print(cauchy_matrix)

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4       ]
 [ 0.4         0.66666667  2.         -2.         -0.66666667]
 [ 0.28571429  0.4         0.66666667  2.         -2.        ]]


48. Print the minimum and maximum representable value for each numpy scalar type

In [162]:
# Iterate through NumPy's built-in scalar types
for dtype in [np.bool_, np.byte, np.ubyte, np.short, np.ushort, np.intc, np.uintc, np.int_, np.uint, np.longlong, np.ulonglong,
              np.half, np.single, np.double, np.longdouble, np.complex64, np.complex128, np.clongdouble]:
    try:
        if np.issubdtype(dtype, np.integer):
            info = np.iinfo(dtype)
            print(f"{dtype.__name__}: Min = {info.min}, Max = {info.max}")
        elif np.issubdtype(dtype, np.floating):
            info = np.finfo(dtype)
            print(f"{dtype.__name__}: Min = {info.min}, Max = {info.max}")
        elif np.issubdtype(dtype, np.complexfloating):
             info = np.finfo(dtype)
             print(f"{dtype.__name__}: Min_real = {info.min}, Max_real = {info.max}, Min_imag = {info.min}, Max_imag = {info.max}")
        else:
            print(f"{dtype.__name__}: No min/max info available")
    except Exception as e:
        print(f"Could not retrieve info for {dtype.__name__}: {e}")

bool: No min/max info available
int8: Min = -128, Max = 127
uint8: Min = 0, Max = 255
int16: Min = -32768, Max = 32767
uint16: Min = 0, Max = 65535
int32: Min = -2147483648, Max = 2147483647
uint32: Min = 0, Max = 4294967295
int64: Min = -9223372036854775808, Max = 9223372036854775807
uint64: Min = 0, Max = 18446744073709551615
longlong: Min = -9223372036854775808, Max = 9223372036854775807
ulonglong: Min = 0, Max = 18446744073709551615
float16: Min = -65504.0, Max = 65504.0
float32: Min = -3.4028234663852886e+38, Max = 3.4028234663852886e+38
float64: Min = -1.7976931348623157e+308, Max = 1.7976931348623157e+308
longdouble: Min = -inf, Max = inf
complex64: Min_real = -3.4028234663852886e+38, Max_real = 3.4028234663852886e+38, Min_imag = -3.4028234663852886e+38, Max_imag = 3.4028234663852886e+38
complex128: Min_real = -1.7976931348623157e+308, Max_real = 1.7976931348623157e+308, Min_imag = -1.7976931348623157e+308, Max_imag = 1.7976931348623157e+308
clongdouble: Min_real = -inf, Max_rea

49. How to print all the values of an array?

In [163]:
# Create a large array
large_array = np.arange(200).reshape(10, 20)

# By default, NumPy might not print all elements
print("Default printing:")
print(large_array)

# Set print options to print all elements
np.set_printoptions(threshold=np.inf)

print("\nPrinting with threshold=np.inf:")
print(large_array)

Default printing:
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
   38  39]
 [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
   58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99]
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
  138 139]
 [140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
  158 159]
 [160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177
  178 179]
 [180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
  198 199]]

Printing with threshold=np.inf:
[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22

50. How to find the closest value (to a given scalar) in a vector?

In [164]:
vector = np.array([1, 5, 8, 12, 15, 20])
scalar = 10

# Calculate the absolute difference between each element and the scalar
absolute_difference = np.abs(vector - scalar)

# Find the index of the minimum absolute difference
closest_index = np.argmin(absolute_difference)

# Get the value from the original vector at the closest index
closest_value = vector[closest_index]

print("Vector:", vector)
print("Scalar:", scalar)
print("Closest value in the vector:", closest_value)

Vector: [ 1  5  8 12 15 20]
Scalar: 10
Closest value in the vector: 8
