1. Import the numpy package under the name np

In [78]:
import numpy as np

2. Print the numpy version and the configuration

In [ ]:
print(np.__version__)
print(np.show_config())

3. Create a null vector of size 10

In [ ]:
null_vector = np.zeros(10)
print(null_vector)

4. How to find the memory size of any array

In [ ]:
print(null_vector.nbytes)

5. How to get the documentation of the numpy add function from the command line?

In [ ]:
help(np.add)

# Or you can use:
np.info(np.add)

6. Create a null vector of size 10 but the fifth value which is 1

In [ ]:
null_vector1 = np.zeros(10)
null_vector1[4] = 1
print(null_vector1)

7. Create a vector with values ranging from 10 to 49

In [ ]:
num_vec = np.arange(10,49)
print(num_vec)

8. Reverse a vector (first element becomes last) 

In [ ]:
reversed_vec = num_vec[::-1]
print(reversed_vec)

9. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
np.arange(9).reshape(3, 3)

10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)
print(indices)

11. Create a 3x3 identity matrix

In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)

12. Create a 3x3x3 array with random values

In [ ]:
np.random.rand(3,3,3)

13. Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
rand = np.random.rand(10,10)
print(rand)
print("The Minimum is: ", rand.min())
print("The Maximum is: ", rand.max())

14. Create a random vector of size 30 and find the mean value

In [ ]:
print(np.random.rand(30))
np.random.rand(30).mean()

15. Create a 2d array with 1 on the border and 0 inside

In [ ]:
border_array = np.ones((5, 5), dtype=int)
border_array[1:-1, 1:-1] = 0
print(border_array)

16. How to add a border (filled with 0's) around an existing array?

In [ ]:
padded_array = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(padded_array)

17. What is the result of the following expression?

0 * np.nan<br>
np.nan == np.nan<br>
np.inf > np.nan<br>
np.nan - np.nan<br>
np.nan in set([np.nan])<br>
0.3 == 3 * 0.1

In [ ]:
print(0 * np.nan)             
print(np.nan == np.nan)       
print(np.inf > np.nan)        
print(np.nan - np.nan)        
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
matrix = np.diag([1, 2, 3, 4], k=-1)
print(matrix)

19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
np.unravel_index(100, (6, 7, 8))

21. Create a checkerboard 8x8 matrix using the tile function

In [79]:
checkerboard_tile = np.tile([[0, 1], [1, 0]], (4, 4))
print(checkerboard_tile)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
checkerboard_tile = 